overblog_graphql:
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -   type: annotation
                    dir: "%kernel.project_dir%/src/Entity"
                    suffix: ~
                -   type: annotation
                    dir: "%kernel.project_dir%/src/GraphQL"
                    suffix: ~
