name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
      
    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: xdebug
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --optimize-autoloader
      env:
        APP_ENV: test
  
    - name: Install JS dependencies
      run: yarn install
    
    - name: Build JS dependencies
      run: yarn build

    - name: Run frontend linter
      run: yarn lint:quiet

    - name: Run backend linter
      run: composer lint

    - name: Run frontend linter
      run: yarn test:coverage

    - name: Run backend tests
      run: composer test

    - name: Warmup dev cache
      run: php bin/console cache:warmup --env=dev
      
    - name: Run static code analyser on backend
      run: composer analyse
      
    - name: Run static code analyser on frontend
      run: yarn analyse

    - name: fix code coverage paths
      working-directory: ./var/reports
      run: |
        sed -i 's/\/home\/runner\/work\/spicy-hamster\/spicy-hamster\//\/github\/workspace\//g' phpunit.xml
        sed -i 's/\/home\/runner\/work\/spicy-hamster\/spicy-hamster\//\/github\/workspace\//g' phpunit.coverage.xml
        sed -i 's/\/home\/runner\/work\/spicy-hamster\/spicy-hamster\//\/github\/workspace\//g' lcov.info

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
